application:
  port: 9002

mongo:
 username: ""
 password: ""
 port: 27017
 host: "10.20.30.20"
 db: "bloodhound"
 collection: "bands"
 require_auth: false

redis:
  url: "redis://10.20.30.5:6379"
  pool_max_open: 16
  pool_max_idle: 8
  pool_timeout_seconds: 1
  pool_expire_seconds: 60

sqlite:
  path: "senzor.db"
  schema: "static/schema.sql"
  